// <auto-generator/>

namespace ProjectPQ.addons.localizers.Maps;

public static class LangKey
{
    public const string RELIC_APPRAISAL_DETAIL_APPRAISAL_NAME = "RELIC_APPRAISAL_DETAIL_APPRAISAL_NAME";
    public const string RELIC_APPRAISAL_HISTORY_RESTORATION_NAME = "RELIC_APPRAISAL_HISTORY_RESTORATION_NAME";
    public const string RELIC_APPRAISAL_PRELIMINARY_APPRAISAL_NAME = "RELIC_APPRAISAL_PRELIMINARY_APPRAISAL_NAME";
    public const string RELIC_APPRAISAL_SURFACE_SURVERY_NAME = "RELIC_APPRAISAL_SURFACE_SURVERY_NAME";
    public const string RELIC_APPRAISAL_UNIDENTIFIED_NAME = "RELIC_APPRAISAL_UNIDENTIFIED_NAME";
    public const string RELIC_PRESERVATION_DAMAGED_NAME = "RELIC_PRESERVATION_DAMAGED_NAME";
    public const string RELIC_PRESERVATION_DESTROYED_NAME = "RELIC_PRESERVATION_DESTROYED_NAME";
    public const string RELIC_PRESERVATION_INTACT_NAME = "RELIC_PRESERVATION_INTACT_NAME";
    public const string RELIC_PRESERVATION_PIECE_NAME = "RELIC_PRESERVATION_PIECE_NAME";
    public const string RELIC_PRESERVATION_PRESERVED_NAME = "RELIC_PRESERVATION_PRESERVED_NAME";
    public const string RELIC_PRESERVATION_WORN_OUT_NAME = "RELIC_PRESERVATION_WORN_OUT_NAME";
    public const string UPGRADES_HALL_EXPANSION_HI = "UPGRADES_HALL_EXPANSION_HI";
}
